# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 599)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("#loginFrame{\n"
"background-image:url(:/Login/output-onlinepngtools.png);\n"
"padding:10px 70px 15px 70px;\n"
"}\n"
"#emailinp{\n"
"height:25px;\n"
"margin-top:10px;\n"
"border:2px solid black;\n"
"border-radius : 6px;\n"
"padding:5px 15px;\n"
"}\n"
"#passwordinp{\n"
"height:25px;\n"
"margin-top:10px;\n"
"border:2px solid black;\n"
"border-radius : 6px;\n"
"padding:5px 15px;\n"
"}\n"
"#emailinp:hover,#passwordinp:hover{\n"
"border:2px solid gray;\n"
"}\n"
"\n"
"#emailinp:focus{\n"
"border:2px solid blue;\n"
"}\n"
"#passwordinp:focus{\n"
"border:2px solid blue;\n"
"}\n"
"#loginbtn{\n"
"margin-top:15px;\n"
"height:25px;\n"
"width:50px;\n"
"color:black;\n"
"background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(20,47,78,20),stop:1 rgba(85,98,112,250));\n"
"border-radius:5px;\n"
"}\n"
"#loginbtn:pressed {\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(112,112,112,255);\n"
"    border-postion:calc(100% -10px)center;\n"
"}\n"
"#loginbtn:hover {\n"
"    background-color:rgba(112,112,112,255);\n"
"}\n"
"#forgotbtn{\n"
"margin-top:5px;\n"
"height:20px;\n"
"color:black;\n"
"border-radius:0px;\n"
"}\n"
"#forgotbtn:pressed {\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgb(255, 0, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.loginFrame = QtWidgets.QFrame(self.centralwidget)
        self.loginFrame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginFrame.setStyleSheet("")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.loginFrame)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget_5)
        self.loginimg = QtWidgets.QLabel(self.loginFrame)
        self.loginimg.setAlignment(QtCore.Qt.AlignCenter)
        self.loginimg.setObjectName("loginimg")
        self.verticalLayout.addWidget(self.loginimg)
        self.widget = QtWidgets.QWidget(self.loginFrame)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.emailinp = QtWidgets.QLineEdit(self.widget)
        self.emailinp.setMinimumSize(QtCore.QSize(300, 0))
        self.emailinp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.emailinp.setObjectName("emailinp")
        self.horizontalLayout.addWidget(self.emailinp)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.loginFrame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.passwordinp = QtWidgets.QLineEdit(self.widget_2)
        self.passwordinp.setMinimumSize(QtCore.QSize(300, 0))
        self.passwordinp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordinp.setObjectName("passwordinp")
        self.horizontalLayout_2.addWidget(self.passwordinp)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.loginFrame)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.forgotbtn = QtWidgets.QPushButton(self.widget_3)
        self.forgotbtn.setObjectName("forgotbtn")
        self.horizontalLayout_3.addWidget(self.forgotbtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.loginFrame)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.loginbtn = QtWidgets.QPushButton(self.widget_4)
        self.loginbtn.setMinimumSize(QtCore.QSize(150, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Login/icons8-enter-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginbtn.setIcon(icon)
        self.loginbtn.setObjectName("loginbtn")
        self.horizontalLayout_4.addWidget(self.loginbtn)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.widget_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.gridLayout.addWidget(self.loginFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Login/ARM_LOGO_Crop-removebg-preview.png\"/></p></body></html>"))
        self.loginimg.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Login/user (2).png\"/></p></body></html>"))
        self.emailinp.setPlaceholderText(_translate("MainWindow", "@gmail.com"))
        self.passwordinp.setPlaceholderText(_translate("MainWindow", "Password"))
        self.forgotbtn.setText(_translate("MainWindow", "Forgot your password?"))
        self.loginbtn.setText(_translate("MainWindow", "login"))
import login_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
